### ISSUE TITLE
Help needed! Version mmenu 5.4.2 doesn't work with Roots Sage anymore.

### ISSUE THREAD

**Issue by coffeeneed** [BeSite/jQuery.mmenu#431] opened 2015-09-18 10:16 UTC
I'm using jQuery.mmenu 5.3.4 (which it says is required by Roots Sage) on a couple of  sites, everything works flawlessly, but when upgrading to mmenu 5.4.2, the menu breaks by not showing or rendering anything inside the container fired with mmenu: ($("#my-menu") (this div is rendered, but is empty). However, the mobile view works without problems.

I don't have enough experience to figure this out by myself, but I recon it has something to do with the clone ability, which we're ordered to use when reading the docs. Nor do I know whom to contact or "blame", is it Sage fault or is it jQuery.mmenu?

I know you suggest using the Wordpress plugin, but this used to work and I would really like to know what's going on and solve this without using any plugins.

What has changed in the newest version, 5.4.2?

I would be very happy if I could use the latest version of this plugins with Roots Sage and also hoping that someone else experienced the same problem and can help me out.

Any ideas?

**Comment by mediatack** [comment] 2015-09-22 10:21
There seems to be a problem with the clone option. This is the first time i use this plugin and i thought i did something wrong...  but i just build a very simple menu and also get like you an empty original-menu-div when using clone. So i made some debugs and looked in the latest commits and i think the problem is inside oncanvas.js code. The panels need to be initiated AFTER initMenu because the clone code is embedded inside initMenu. The latest version update changed the order...

![mmenu-clone-bug](https://cloud.githubusercontent.com/assets/5080994/10015943/aeed9788-6123-11e5-9935-1014b4a233ef.PNG)

**Comment by FrDH** [comment] 2015-09-22 11:07
I'll see if I can reproduce the issue and fix it.

**Comment by FrDH** [comment] 2015-09-22 19:45
I see the issue but the line was moved for a reason. Can't simply move it back. I'll try and find a solution. Thanks for debugging :)

**Comment by coffeeneed** [comment] 2015-09-22 20:18
Hi, both, and thanks for the follow up. Will be good to be back on track!

**Comment by FrDH** [comment] 2015-09-22 21:21
Should be fixed in version 5.4.3

**Comment by FrDH** [comment] 2015-09-24 19:48
Could you please try the update and confirm if this update fixes the issue so I can close this issue?

**Comment by mediatack** [comment] 2015-10-05 07:23
Just updated to latest version 5.5.2 and cloning works fine now. Thanks for the fast bugfix :)

**Closed** 2015-10-10 19:01 UTC
