### ISSUE TITLE
Scroll bug on iPhone 6 / iOS 8

### ISSUE THREAD

**Issue by renouille** [BeSite/jQuery.mmenu#332] opened 2015-04-07 10:08 UTC
Regularly when scrolling on the menu, the menu doesn't move but the page content does instead. It is as if the focus is still on the content and not on the menu.

Only way to get the menu to scroll when this happen is to close and reopen the menu or to keep scrolling until the menu randomly get the focus.

Does only happen on iPhone/iPods with iOS 8, not on Android.
I have no min-height set, nor changed the css of mmenu.

Happens also on the demo page: http://mmenu.frebsite.nl/demo/index.html?demo=menu-onepage
(Even if the menu is not long enough to be scrollable, I think it is the same issue)

Any ideas ?

**Comment by FrDH** [comment] 2015-04-09 10:49
If the menu is not long enough to be scrollable, touch-screens might start scrolling the page. If they wouldn't, you'd probably get a lot of issues in other parts of websites. There is not much I can do about that without introducing a whole new range of issues. 

If the menu is long enough to be scrollable, the menu should scroll. But again, there is not much I can do to stop the page from scrolling.

FYI, all examples on the website seem to scroll as expected on my iPhone 6 with iOS 8.

**Comment by Master-Oliveira** [comment] 2015-04-15 11:07
Same happens to me. I'm pretty sure it has something to do with the -webkit-overflow-scrolling "bug".

(as in here https://github.com/scottjehl/Device-Bugs/issues/14)

**Comment by FrDH** [comment] 2015-04-17 07:06
iOS5 doesn't support scrolling in a fixed div. iOS5 is really old, even an iPhone 3Gs can be updated to iOS6. So if that indead is the issue, I'm not going to spend time to fix it (couldn't do any testing anyway).

**Comment by Master-Oliveira** [comment] 2015-04-17 09:32
Im testing it on a iPhone 6 and Samsung S5 and the problem is on both, but its easier to reproduce on the iphone 6. I can reproduce the same behavior on the mmenu demos online (just open the page http://mmenu.frebsite.nl/demo/index.html?demo=menu-onepage on a iphone 6, and you can see the vertical scroll problem). If you need more info, os PS I can help. 

It looks like the problem disappears when the menu activates the vertical scroll.

**Comment by FrDH** [comment] 2015-04-26 19:26
I tested that demo on my iPhone 6 but could not reproduce the issue.
If you find anything that might help, please let me know.

**Comment by nolawi** [comment] 2015-05-26 15:10
this is an issue for me as well!

**Comment by tolousn** [comment] 2015-06-10 18:24
Same here.  Looks like the mmenu is loosing focus after it is open.
1. Menu is open and it's long enough that scroll is applied.  
2. Move the menu up and down few times, it might take few finger swipes for it to mess up.  At first menu might move up and down, then the menu gets stuck and page moves up and down.  The only way to regain focus is press and hold on the menu for a moment and then you can scroll it again.

Many times issue happens as soon as the menu is loaded, sometimes it takes a moment for the bug to appear.

Using iOS 8 / iPhone 6 / Safari.  I was unable to recreate this in Chrome browser on the same device.
If there's anything else I can do to help, let me know.

**Comment by nolawi** [comment] 2015-06-23 18:28
I fixed it on my end. Let me know if you want me to contribute to the repo

**Comment by Master-Oliveira** [comment] 2015-06-24 08:55
Great news! Please can you publish or send the fix? I really need that problem fixed on my project.

Thanks

Enviado do meu Windows Phone

-----Original Message-----

**Comment by lonwi** [comment] 2015-07-23 14:35
Any progress on this? I noticed this on Android Phones.

**Comment by rohandaxini** [comment] 2015-09-08 13:09
hi @nolawi did you push the fix to the repo? That fix would help us.

**Comment by xpur** [comment] 2015-09-22 15:28
hi. any body fix this issue? please help.

**Comment by rohandaxini** [comment] 2015-09-22 15:31
@xpur I am not sure, but I had to move away from mmenu due to this weird issue. Sorry :(
I love this mmenu but until its fixed or pushed to stable version can't use it. I moved to use menu from foundation

**Comment by agfa555** [comment] 2015-09-24 14:26
Same problem hereon an iPhone 5S & iPhone 6 running iOS8, any progress? I might have to implement another menu too. :(

**Comment by Legin76** [comment] 2015-10-14 10:02
I'm having issues with this too.

**Comment by keminx** [comment] 2015-11-23 11:10
Hi, is there any news?

**Closed** 2015-12-17 12:03 UTC

**Comment by agfa555** [comment] 2015-12-18 09:26
Why close it while it still happens?

**Comment by hirokimu** [comment] 2016-01-10 04:52
This is my dirty workaround but seems work well.

```javascript
$(function(){
	var isMenuOpened = false;
	var menuScrollElementId = "#mm-1";

	var menu = $("Your mmenu element").data("mmenu");

	//do not use <a href="#my-menu">Open the menu</a>
   	$("Your menu button element").click(function(){
		isMenuOpened = true;
		menu.open();
		$(menuScrollElementId).scrollTop(0);
		return false;
    });

	menu.bind("opened", function () {
		isMenuOpened = true;
	});
	menu.bind("closed", function () {
		isMenuOpened = false;
	});

	//prevent body scroll
	$(document).on("touchmove", function(e) {
		if (isMenuOpened) e.preventDefault();
	});
	$("body").on("touchstart", menuScrollElementId, function(e) {
		if (!isMenuOpened) return;
		if (e.currentTarget.scrollTop === 0) {
			e.currentTarget.scrollTop = 1;
		}
		else if (e.currentTarget.scrollHeight === e.currentTarget.scrollTop + e.currentTarget.offsetHeight) {
	    	e.currentTarget.scrollTop -= 1;
	    }
	});
	$("body").on("touchmove", menuScrollElementId, function(e) {
		if (!isMenuOpened) return;
		if ($(this)[0].scrollHeight > $(this).innerHeight()) e.stopPropagation();
	});

	//fix issue after device rotation change
	$(window).on("orientationchange", function() {
		$(menuScrollElementId).scrollTop(0);
		$(menuScrollElementId).css({ "-webkit-overflow-scrolling":"auto" });
		$(menuScrollElementId).css({ "-webkit-overflow-scrolling":"touch" });
	});
});
```

based on http://stackoverflow.com/a/14244680/3743119

**Comment by agfa555** [comment] 2016-01-11 04:50
It works!!!
Thank a lot @hirokimu!!!!!

**Comment by FrDH** [comment] 2016-01-13 08:50
Thanks for taking the time to find a solution.
I'll see if I can create an add-on out of this.

**Comment by FrDH** [comment] 2016-01-13 09:57
Could anyone confirm this issue ONLY appears on iOS ? 
If so, it could be included by default and used on iOS only.

**Comment by Master-Oliveira** [comment] 2016-01-13 10:12
Im testing it on a iPhone 6 and Samsung S5 and the problem is on both, but its easier to reproduce on the iphone 6. I can reproduce the same behavior on the mmenu demos online (just open the page http://mmenu.frebsite.nl/demo/index.html?demo=menu-onepage on a iphone 6, and you can see the vertical scroll problem)

**Comment by Legin76** [comment] 2016-01-13 11:06
I've just tested the demos ios, safari and chrome and it does happen in both and on android in chrome but not firefox but I think this may be because the demos menus are not long enough to scroll.

It did not happen on the main menu on http://mmenu.frebsite.nl on any of them.

I think to be sure it needs to be tested on pages that have both long menus and content long enough to scroll.

**Comment by hirokimu** [comment] 2016-01-15 21:25
@FrDH Thank you for your nice project. I could reproduce this issue on mmenu.frebsite.nl with my Nexus6/Chrome. But iOS is much easier to reproduce.

**Comment by metaskills** [comment] 2016-03-04 01:29
FWIW, I found that using the scrollBugFix add-on helped, but it had a bug in it. See https://github.com/FrDH/jQuery.mmenu/issues/532
